[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

# quote内のプログラムをシンタックスハイライトする
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

# マークダウンのシンタックスハイライト
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']#このファイル形式で開いたときのみロードされる

# 編集中のMarkdownファイルのプレビューを作成する
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']#このファイル形式で開いたときのみロードされる

# プレビューをブラウザで開いてくれる
[[plugins]]
repo = 'tyru/open-browser.vim'

# vimでフローチャートとかシーケンス図を書くためのUMLをサポート
[[plugins]]
repo = 'aklt/plantuml-syntax'

# nvimでPlantUMLを開く
[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'
